[build]
  command = "npm run build"
  publish = ".netlify/functions-internal/server"
  edge_functions = "true"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 